### ISSUE TITLE
Wrong week number

### ISSUE THREAD

**Issue by someonedead** [bartkessels/daily-note-calendar#30] opened 2024-12-03 14:20 UTC
When I click on 53 week of this year, I get 2024-W01, which is not right for sure.

I assume the best approach would be to make it 2025-W01.

**Comment by bartkessels** [comment] 2024-12-03 16:08
Hello, thank you for submitting this issue. It’s a bit of a tricky issue but I’ll try to fix it as soon as possible. For now I’ve been able to reproduce it (which isn’t that hard), so I’ll start on finding a proper fix for the issue. 

Hopefully it’ll come in the next minor release, but since I don’t know how this can be fixed yet I cam’t promise anything. Hopefully this will work for now, but I want to fix it as soon as possible.

**Comment by bartkessels** [comment] 2024-12-04 05:54
This issue has been resolved in version 1.6.4 of the plugin, the release should be available to you shortly.

Again, thanks for your feedback and if you have any other issues or suggestions feel free to open another issue.

**Closed by bartkessels** 2024-12-04 05:54 UTC
