### ISSUE TITLE
First row of calendar dates incorrectly aligned

### ISSUE THREAD

**Issue by LesWaymont** [bartkessels/daily-note-calendar#51] opened 2024-12-24 13:51 UTC
Hi Bart - just noticed in 1.10.1 the the first row of dates in the calendar is aligned to the left, but should be aligned right...
![Screenshot 2024-12-24 at 13 49 25](https://github.com/user-attachments/assets/d457e655-6e23-448c-af05-b566487c2bb6)

Otherwise, I'm enjoying this plugin - thanks!

**Comment by bartkessels** [comment] 2024-12-25 09:30
Hello, thank you for opening this bug. I haven’t seen this one yet, could you tell me what your settings for Daily Note Plugin are, and if uou have custom css or which theme your using?

Because I either suspect that something is wrong with the settings or that some theme or css interferes with the layout of the dates. Either way, I’ll be looking into it and going to fix it.

Anyway, glad to hear you enjoy using this plugin. Hopefully we can resolve this bug quickly.

**Comment by bartkessels** [comment] 2024-12-27 11:17
In the upcoming update (version 1.11.0) I've updated the view a little because I noticed that that days that don't fall into the current month would still have an element without a date in it. In the new version, dates that don't belong to the current month don't have an element anymore, so this might also fix your issue.

**Comment by LesWaymont** [comment] 2024-12-28 13:11
￼
Hi Bart
￼
￼


As you can see, the incorrect alignment issue remains own 1.11.0 (in the example below, the 1st December should be a Sunday, not a Monday as shown).
I have the same behaviour in desktop (Mac) and mobile (iPhone) verisions.
I have the same result regardless of theme, and I have no oddball css snippets (that I’m aware of!)
I’ve attached the files from the plugin directory for reference

Regards
Les


￼

________________
Mac mini M2Pro / Mail

**Comment by bartkessels** [comment] 2024-12-30 09:32
Hello Les,

Unfortunately the attachments got lost in the mail, because I can't see them in Github. Could you perhaps upload them on Github?

Regards,

Bart

**Comment by LesWaymont** [comment] 2024-12-30 09:40
[data.json](https://github.com/user-attachments/files/18273572/data.json)
[manifest.json](https://github.com/user-attachments/files/18273573/manifest.json)

**Comment by bartkessels** [comment] 2024-12-31 09:01
Hello, I've just downloaded you `data.json` and `manifest.json` files and I have the same behaviour as you. That is good news because that means that the issue is the plugin itself and not another theme or custom css.

I will try to find the bug and create a new release. Thanks for providing these files!

**Comment by bartkessels** [comment] 2024-12-31 10:16
Okay, I just found the bug. It was some logic that would not be executed if the periodic note indicator was disabled. This explains why I couldn't reproduce it because I had the setting enabled.

I've just fixed it in the plugin and it will be released with version 1.11.1. Thanks for providing the feedback and your setting files.

**Comment by bartkessels** [comment] 2024-12-31 10:29
Version 1.11.1 has just been released. So the next time you update the plugin, this bug should be gone.

As always, thanks for reporting this issue. If you encounter any other bugs or have some ideas to improve the plugin feel free to open an issue.

**Closed by bartkessels** 2024-12-31 10:29 UTC

**Comment by LesWaymont** [comment] 2025-01-02 09:18
Excellent - thanks!________________Mail / iPhone 15On 31 Dec 2024, at 10:30, Bart Kessels ***@***.***> wrote:﻿
Closed #51 as completed.
