### ISSUE TITLE
A calendar has troubles with year transition

### ISSUE THREAD

**Issue by someonedead** [bartkessels/daily-note-calendar#29] opened 2024-12-03 14:11 UTC
I get a strange calendar behaviour when switching between months

When I switch to January from December 2024, it shows January 2024. But I get the right date if I switch to it from February.

Same with December: if I switch to it from January, it shows December 2025 (what year is shown on January is not important). When I switch from November, the date is right.

![изображение](https://github.com/user-attachments/assets/62f57aa3-da34-4efa-b2ca-fb5e8e33c387)
![изображение](https://github.com/user-attachments/assets/708265c6-bcc1-4c78-8cb9-a26d67fb5734)

**Comment by bartkessels** [comment] 2024-12-03 16:05
Hello, thank you for your feedback! I’ve been able to reproduce the issue and I know where it is, so in the next minor release this will be addressed. 

This release will come pretty quickly because it’s a quite annoying bug. 

For now, thanks for your feedback and feel free to submit more issues or ideas. I’ve already seen your other issue, so that’s good! Thank you!

**Comment by bartkessels** [comment] 2024-12-04 05:54
This issue has been resolved in version 1.6.4 of the plugin, the release should be available to you shortly.

Again, thanks for your feedback and if you have any other issues or suggestions feel free to open another issue.

**Closed by bartkessels** 2024-12-04 05:54 UTC
